global:
  scrape_interval: 15s

scrape_configs:
  - job_name: yacy-rwi-node
    static_configs:
      - targets: ["yacy-rwi-node:9090"]

  - job_name: renderproxy
    static_configs:
      - targets: ["renderproxy:9090"]

  - job_name: yacycrawler
    static_configs:
      - targets: ["yacycrawler:9090"]

  - job_name: yacydhtsearch
    static_configs:
      - targets: ["yacydhtsearch:9090"]

  - job_name: visitcrawl
    static_configs:
      - targets: ["visitcrawl:9091"]

  - job_name: corpustext
    static_configs:
      - targets: ["corpustext:9090"]

  - job_name: nats
    static_configs:
      - targets: ["nats-metrics:7777"]

  - job_name: corpusmarkdown
    static_configs:
      - targets: ["corpusmarkdown:9090"]

  - job_name: webresearchmcp
    static_configs:
      - targets: ["webresearchmcp:9090"]
